### ISSUE TITLE
App.vue Line 32: "working" -> "mute"

### ISSUE THREAD

**Issue by eltoro0815** [anthonygore/vue-laravel-crud#4]
![image](https://user-images.githubusercontent.com/18168608/51849394-e71e6d00-231f-11e9-8aec-da863324bfb9.png)
![image](https://user-images.githubusercontent.com/18168608/51849444-06b59580-2320-11e9-86ff-80db4f5c86d5.png)

**Comment by eltoro0815** [comment]
The word "working" has to be replaced with "mute".

**Comment by anthonygore** [comment]
Thanks, resolved in latest update
